"""
Transfer Learning Data Efficiency Experiment
=============================================
Goal: Determine the minimum number of female simulation samples needed
to achieve good predictions when leveraging a pre-trained male RF model.

Experimental design:
- Male source model: pre-trained on ~360k male samples
- Female data: generated from MATLAB beam+membrane simulation with female geometry
- Fixed test set (4000 samples) for stable evaluation
- Training pool (remaining samples) subsampled at varying sizes
- 10 repeated draws per size for statistical robustness

Methods compared:
0. Female-only baseline (no transfer)
1. Source-only (male model applied directly)
2. Linear calibration (linear transform of male predictions)
3. Residual RF (learn male model's error pattern)
4. Feature augmentation (male predictions as extra input features)
5. TransRF ensemble (learned-weight combination of methods 0, 3, 4)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, LinearRegression
import joblib
import os
import warnings
warnings.filterwarnings('ignore')


# ==================== CONFIGURATION ====================
TRAINING_SIZES = [10, 25, 50, 100, 250, 500, 1000]
N_RUNS = 10
RANDOM_STATE = 42
TEST_SET_SIZE = 4000

# paths (relative to this script)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MALE_MODEL_PATH = os.path.join(SCRIPT_DIR, 'models', 'RF_BCM.pkl')
MALE_SCALER_PATH = os.path.join(SCRIPT_DIR, 'models', 'x_scaler_BCM.pkl')

# MATLAB output — change this to wherever you copied it
FEMALE_DATA_PATH = '/tmp/Female_Membrane_Beam_Model.txt'

OUTPUT_DIR = os.path.join(SCRIPT_DIR, 'transfer-figs')


# ==================== DATA LOADING ====================
def load_female_data(path):
    """Load female data generated by MATLAB simulation"""
    df = pd.read_csv(path, delim_whitespace=True)

    # rename columns to match the male model's expected names
    col_map = {
        'a_LCA': 'a_LCA',
        'a_IA': 'a_IA',
        'a_PCA': 'a_PCA',
        'a_CT': 'a_CT',
        'a_TA': 'a_TA',
        'Ps': 'PS',       # MATLAB header: "Ps (Pa)" may get truncated
        'F0': 'F0',       # MATLAB header: "F0 (Hz)"
        'SPL': 'SPL',     # MATLAB header: "SPL (dB)"
    }

    # handle MATLAB's potentially truncated column names
    renamed = {}
    for col in df.columns:
        clean = col.strip()
        if 'Ps' in clean or 'PS' in clean:
            renamed[col] = 'PS'
        elif 'F0' in clean:
            renamed[col] = 'F0'
        elif 'SPL' in clean:
            renamed[col] = 'SPL'
        elif 'a_CT' in clean:
            renamed[col] = 'a_CT'
        elif 'a_TA' in clean:
            renamed[col] = 'a_TA'
        else:
            renamed[col] = clean

    df = df.rename(columns=renamed)

    # drop failed simulations (NaN in F0 or SPL)
    df = df[['a_CT', 'a_TA', 'PS', 'F0', 'SPL']].dropna()

    # drop rows where F0 or SPL are unreasonable
    df = df[(df['F0'] > 0) & (df['F0'] < 2000)]
    df = df[(df['SPL'] > 0) & (df['SPL'] < 200)]

    df = df.reset_index(drop=True)
    return df


# ==================== ADAPTIVE MODEL COMPLEXITY ====================
def get_rf_params(n_samples):
    """Scale RF complexity to the available training data"""
    if n_samples < 30:
        return {'n_estimators': 20, 'max_depth': 3, 'min_samples_leaf': 5}
    elif n_samples < 75:
        return {'n_estimators': 50, 'max_depth': 5, 'min_samples_leaf': 3}
    elif n_samples < 200:
        return {'n_estimators': 100, 'max_depth': 8, 'min_samples_leaf': 2}
    elif n_samples < 500:
        return {'n_estimators': 200, 'max_depth': 12, 'min_samples_leaf': 2}
    else:
        return {'n_estimators': 300, 'max_depth': None, 'min_samples_leaf': 1}


# ==================== TRANSFER LEARNING METHODS ====================

def method_female_only(X_train, Y_train, X_test):
    """Method 0: Train RF only on female data (baseline to beat)"""
    params = get_rf_params(len(X_train))
    scaler = StandardScaler()
    X_tr = scaler.fit_transform(X_train)
    X_te = scaler.transform(X_test)

    rf = MultiOutputRegressor(
        RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1, **params)
    )
    rf.fit(X_tr, Y_train)
    return rf.predict(X_te)


def method_source_only(X_test, male_model, male_scaler):
    """Method 1: Apply male model directly to female inputs (no female data used)"""
    X_te = male_scaler.transform(X_test)
    return male_model.predict(X_te)


def method_linear_calibration(X_train, Y_train, X_test, male_model, male_scaler):
    """
    Method 2: Linear calibration of male predictions.

    Learns: Y_female = A * [male_pred, inputs] + b
    Very few parameters, so works with N=10.
    """
    # get male predictions on training and test data
    pred_male_train = male_model.predict(male_scaler.transform(X_train))
    pred_male_test = male_model.predict(male_scaler.transform(X_test))

    pred = np.zeros((len(X_test), 2))

    for i, target in enumerate(['F0', 'SPL']):
        # features for calibration: male prediction + original inputs
        cal_features_train = np.column_stack([
            pred_male_train[:, i],
            X_train.values
        ])
        cal_features_test = np.column_stack([
            pred_male_test[:, i],
            X_test.values
        ])

        # Ridge regression (regularised to prevent overfitting with small N)
        alpha = max(1.0, 100.0 / len(X_train))  # more regularisation for smaller N
        reg = Ridge(alpha=alpha)
        reg.fit(cal_features_train, Y_train[:, i])
        pred[:, i] = reg.predict(cal_features_test)

    return pred


def method_residual_rf(X_train, Y_train, X_test, male_model, male_scaler):
    """
    Method 3: Train RF to predict the residual (error) of the male model.
    Final prediction = male_prediction + learned_residual
    """
    pred_male_train = male_model.predict(male_scaler.transform(X_train))
    pred_male_test = male_model.predict(male_scaler.transform(X_test))

    residuals = Y_train - pred_male_train

    params = get_rf_params(len(X_train))
    rf = MultiOutputRegressor(
        RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1, **params)
    )
    rf.fit(X_train.values, residuals)

    return pred_male_test + rf.predict(X_test.values)


def method_feature_augmentation(X_train, Y_train, X_test, male_model, male_scaler):
    """
    Method 4: Use male predictions as additional input features.
    Input becomes: (a_CT, a_TA, PS, F0_male, SPL_male) -> (F0, SPL)
    """
    pred_male_train = male_model.predict(male_scaler.transform(X_train))
    pred_male_test = male_model.predict(male_scaler.transform(X_test))

    X_train_aug = np.column_stack([X_train.values, pred_male_train])
    X_test_aug = np.column_stack([X_test.values, pred_male_test])

    params = get_rf_params(len(X_train))
    scaler = StandardScaler()
    X_tr = scaler.fit_transform(X_train_aug)
    X_te = scaler.transform(X_test_aug)

    rf = MultiOutputRegressor(
        RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1, **params)
    )
    rf.fit(X_tr, Y_train)
    return rf.predict(X_te)


def method_transrf_ensemble(X_train, Y_train, X_test, male_model, male_scaler):
    """
    Method 5: Learned-weight ensemble of female-only, residual, and augmented.
    Weights are learned via cross-validation on the training set.
    """
    n = len(X_train)

    # split training data into model-fitting and weight-learning portions
    if n >= 40:
        split_idx = int(0.75 * n)
    else:
        # with very few samples, use all for both (slight optimistic bias, but unavoidable)
        split_idx = n

    X_model, X_weight = X_train.iloc[:split_idx], X_train.iloc[split_idx:]
    Y_model, Y_weight = Y_train[:split_idx], Y_train[split_idx:]

    # get component predictions on weight-learning set and test set
    pred_female_weight = method_female_only(X_model, Y_model, X_weight) if len(X_weight) > 0 else None
    pred_female_test = method_female_only(X_model, Y_model, X_test)

    pred_residual_weight = method_residual_rf(X_model, Y_model, X_weight, male_model, male_scaler) if len(X_weight) > 0 else None
    pred_residual_test = method_residual_rf(X_model, Y_model, X_test, male_model, male_scaler)

    pred_aug_weight = method_feature_augmentation(X_model, Y_model, X_weight, male_model, male_scaler) if len(X_weight) > 0 else None
    pred_aug_test = method_feature_augmentation(X_model, Y_model, X_test, male_model, male_scaler)

    pred_calib_weight = method_linear_calibration(X_model, Y_model, X_weight, male_model, male_scaler) if len(X_weight) > 0 else None
    pred_calib_test = method_linear_calibration(X_model, Y_model, X_test, male_model, male_scaler)

    # learn weights
    pred_ensemble = np.zeros((len(X_test), 2))

    for i in range(2):
        if len(X_weight) >= 5 and pred_female_weight is not None:
            stack = np.column_stack([
                pred_female_weight[:, i],
                pred_residual_weight[:, i],
                pred_aug_weight[:, i],
                pred_calib_weight[:, i],
            ])
            reg = LinearRegression(positive=True, fit_intercept=False)
            reg.fit(stack, Y_weight[:, i])
            w = reg.coef_
            if np.sum(w) > 0:
                w = w / np.sum(w)
            else:
                w = np.array([0.25, 0.25, 0.25, 0.25])
        else:
            # default equal weights for very small N
            w = np.array([0.25, 0.25, 0.25, 0.25])

        stack_test = np.column_stack([
            pred_female_test[:, i],
            pred_residual_test[:, i],
            pred_aug_test[:, i],
            pred_calib_test[:, i],
        ])
        pred_ensemble[:, i] = stack_test @ w

    return pred_ensemble


# ==================== SINGLE EXPERIMENT RUN ====================
def run_single(X_pool, Y_pool, X_test, Y_test, n_train, male_model, male_scaler, seed):
    """Run all methods for a single draw of n_train samples"""

    rng = np.random.RandomState(seed)
    indices = rng.choice(len(X_pool), size=min(n_train, len(X_pool)), replace=False)

    X_train = X_pool.iloc[indices].reset_index(drop=True)
    Y_train = Y_pool[indices]

    X_test_df = X_test.reset_index(drop=True)
    Y_test_arr = Y_test

    results = {}

    # Method 0: female-only baseline
    pred = method_female_only(X_train, Y_train, X_test_df)
    results['female_only'] = pred

    # Method 1: source-only (no female data)
    pred = method_source_only(X_test_df, male_model, male_scaler)
    results['source_only'] = pred

    # Method 2: linear calibration
    pred = method_linear_calibration(X_train, Y_train, X_test_df, male_model, male_scaler)
    results['linear_calib'] = pred

    # Method 3: residual RF
    pred = method_residual_rf(X_train, Y_train, X_test_df, male_model, male_scaler)
    results['residual_rf'] = pred

    # Method 4: feature augmentation
    pred = method_feature_augmentation(X_train, Y_train, X_test_df, male_model, male_scaler)
    results['feature_aug'] = pred

    # Method 5: TransRF ensemble
    pred = method_transrf_ensemble(X_train, Y_train, X_test_df, male_model, male_scaler)
    results['transrf'] = pred

    # compute metrics
    metrics = {}
    for method_name, pred in results.items():
        for i, target in enumerate(['F0', 'SPL']):
            metrics[f'{method_name}_{target}_r2'] = r2_score(Y_test_arr[:, i], pred[:, i])
            metrics[f'{method_name}_{target}_mae'] = mean_absolute_error(Y_test_arr[:, i], pred[:, i])

    return metrics


# ==================== MAIN ====================
def main():
    print("=" * 70)
    print("TRANSFER LEARNING DATA EFFICIENCY EXPERIMENT")
    print("Goal: Minimise female simulation cost via male->female transfer")
    print("=" * 70)

    # --- load male model ---
    print(f"\nLoading male source model from {MALE_MODEL_PATH}")
    if not os.path.exists(MALE_MODEL_PATH):
        print(f"ERROR: Male model not found at {MALE_MODEL_PATH}")
        print("Run MaleRF.py first to train the male model.")
        return
    male_model = joblib.load(MALE_MODEL_PATH)
    male_scaler = joblib.load(MALE_SCALER_PATH)
    print("  Male model loaded.")

    # --- load female data ---
    print(f"\nLoading female data from {FEMALE_DATA_PATH}")
    if not os.path.exists(FEMALE_DATA_PATH):
        print(f"ERROR: Female data not found at {FEMALE_DATA_PATH}")
        print("Run the MATLAB simulation first.")
        return

    df = load_female_data(FEMALE_DATA_PATH)
    print(f"  Loaded {len(df)} valid female samples")
    print(f"  Columns: {df.columns.tolist()}")
    print(f"  F0 range: {df['F0'].min():.1f} - {df['F0'].max():.1f} Hz")
    print(f"  SPL range: {df['SPL'].min():.1f} - {df['SPL'].max():.1f} dB")

    if len(df) < TEST_SET_SIZE + max(TRAINING_SIZES):
        print(f"\nWARNING: Only {len(df)} samples available.")
        print(f"  Need {TEST_SET_SIZE} for test + {max(TRAINING_SIZES)} for training pool.")
        print(f"  Adjusting test set size...")
        test_size = min(TEST_SET_SIZE, int(len(df) * 0.8))
    else:
        test_size = TEST_SET_SIZE

    # --- split into fixed test set and training pool ---
    X_all = df[['a_CT', 'a_TA', 'PS']]
    Y_all = df[['F0', 'SPL']].values

    X_pool, X_test, Y_pool, Y_test = train_test_split(
        X_all, Y_all, test_size=test_size, random_state=RANDOM_STATE
    )
    X_pool = X_pool.reset_index(drop=True)
    X_test = X_test.reset_index(drop=True)

    print(f"\n  Test set:     {len(X_test)} samples (fixed)")
    print(f"  Training pool: {len(X_pool)} samples")

    # filter training sizes to what's available
    valid_sizes = [n for n in TRAINING_SIZES if n <= len(X_pool)]
    print(f"  Training sizes to test: {valid_sizes}")

    # --- check male model baseline ---
    pred_male_all = method_source_only(X_test, male_model, male_scaler)
    r2_male_f0 = r2_score(Y_test[:, 0], pred_male_all[:, 0])
    r2_male_spl = r2_score(Y_test[:, 1], pred_male_all[:, 1])
    print(f"\n  Male model on female data (zero-shot):")
    print(f"    F0 R²:  {r2_male_f0:.4f}")
    print(f"    SPL R²: {r2_male_spl:.4f}")

    # --- run experiments ---
    all_results = []

    for n_train in valid_sizes:
        print(f"\n{'='*50}")
        print(f"  N_train = {n_train}")
        print(f"{'='*50}")

        run_metrics = []

        for run in range(N_RUNS):
            seed = RANDOM_STATE + run
            metrics = run_single(X_pool, Y_pool, X_test, Y_test, n_train,
                                 male_model, male_scaler, seed)
            run_metrics.append(metrics)

            # print progress
            fem_r2 = (metrics['female_only_F0_r2'] + metrics['female_only_SPL_r2']) / 2
            best_transfer = max(
                (metrics['linear_calib_F0_r2'] + metrics['linear_calib_SPL_r2']) / 2,
                (metrics['residual_rf_F0_r2'] + metrics['residual_rf_SPL_r2']) / 2,
                (metrics['feature_aug_F0_r2'] + metrics['feature_aug_SPL_r2']) / 2,
                (metrics['transrf_F0_r2'] + metrics['transrf_SPL_r2']) / 2,
            )
            print(f"  Run {run+1:>2}/{N_RUNS}: Female-only R²={fem_r2:.3f}  Best transfer R²={best_transfer:.3f}")

        # aggregate across runs
        agg = {'n_train': n_train}
        all_keys = run_metrics[0].keys()
        for key in all_keys:
            vals = [m[key] for m in run_metrics]
            agg[f'{key}_mean'] = np.mean(vals)
            agg[f'{key}_std'] = np.std(vals)

        all_results.append(agg)

    # --- results table ---
    print("\n\n" + "=" * 90)
    print("RESULTS SUMMARY — Average R² (mean of F0 and SPL)")
    print("=" * 90)

    methods_display = [
        ('source_only', 'Male Only'),
        ('female_only', 'Female Only'),
        ('linear_calib', 'Linear Calib'),
        ('residual_rf', 'Residual RF'),
        ('feature_aug', 'Feature Aug'),
        ('transrf', 'TransRF Ens'),
    ]

    header = f"{'N':>6} |"
    for _, name in methods_display:
        header += f" {name:>13} |"
    header += f" {'Best Method':>14}"
    print(header)
    print("-" * len(header))

    for r in all_results:
        row = f"{r['n_train']:>6} |"
        method_scores = {}
        for key, name in methods_display:
            avg = (r[f'{key}_F0_r2_mean'] + r[f'{key}_SPL_r2_mean']) / 2
            std = (r[f'{key}_F0_r2_std'] + r[f'{key}_SPL_r2_std']) / 2
            row += f" {avg:>6.3f}±{std:.3f} |"
            method_scores[name] = avg
        best = max(method_scores, key=method_scores.get)
        row += f" {best:>14}"
        print(row)

    # --- improvement over female-only ---
    print("\n\nIMPROVEMENT OVER FEMALE-ONLY BASELINE:")
    print("-" * 70)
    for r in all_results:
        baseline = (r['female_only_F0_r2_mean'] + r['female_only_SPL_r2_mean']) / 2
        print(f"\n  N={r['n_train']:>4} (baseline R²={baseline:.3f}):")
        for key, name in methods_display:
            if key == 'female_only':
                continue
            avg = (r[f'{key}_F0_r2_mean'] + r[f'{key}_SPL_r2_mean']) / 2
            diff = avg - baseline
            status = "BETTER" if diff > 0.005 else ("SAME" if diff > -0.005 else "WORSE")
            print(f"    {name:<14} R²={avg:.3f}  ({diff:+.3f})  {status}")

    # --- find the "transfer learning saves X% of simulations" result ---
    print("\n\nKEY FINDING — SIMULATION COST SAVINGS:")
    print("-" * 70)

    # find the R² achieved by female-only at the largest training size
    largest = all_results[-1]
    target_r2 = (largest['female_only_F0_r2_mean'] + largest['female_only_SPL_r2_mean']) / 2
    print(f"  Female-only with {largest['n_train']} samples achieves R² = {target_r2:.3f}")

    for r in all_results:
        for key, name in methods_display:
            if key in ('source_only', 'female_only'):
                continue
            avg = (r[f'{key}_F0_r2_mean'] + r[f'{key}_SPL_r2_mean']) / 2
            if avg >= target_r2 * 0.95:  # within 5% of the target
                savings = (1 - r['n_train'] / largest['n_train']) * 100
                print(f"  {name} with {r['n_train']} samples achieves R² = {avg:.3f} "
                      f"-> {savings:.0f}% fewer simulations needed")
                break

    # --- visualisation ---
    print("\n\nGenerating plots...")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    n_values = [r['n_train'] for r in all_results]

    # colour and style config
    style = {
        'source_only':  ('gray',   '--', 'Male Only (zero-shot)'),
        'female_only':  ('blue',   '-',  'Female Only (baseline)'),
        'linear_calib': ('orange', '-',  'Linear Calibration'),
        'residual_rf':  ('purple', '-',  'Residual RF'),
        'feature_aug':  ('green',  '-',  'Feature Augmentation'),
        'transrf':      ('red',    '-',  'TransRF Ensemble'),
    }

    # --- Plot 1: R² vs N (average of F0 and SPL) ---
    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle('Transfer Learning Data Efficiency', fontsize=14, fontweight='bold')

    for ax, (targets, title) in zip(axes, [
        (['F0', 'SPL'], 'Average R² (F0 + SPL)'),
        (['F0'], 'F0 R²'),
        (['SPL'], 'SPL R²'),
    ]):
        for key, (color, ls, label) in style.items():
            r2_means = []
            r2_stds = []
            for r in all_results:
                vals = [r[f'{key}_{t}_r2_mean'] for t in targets]
                stds = [r[f'{key}_{t}_r2_std'] for t in targets]
                r2_means.append(np.mean(vals))
                r2_stds.append(np.mean(stds))

            ax.plot(n_values, r2_means, marker='o', color=color,
                    linestyle=ls, linewidth=2, label=label, markersize=6)
            ax.fill_between(n_values,
                            np.array(r2_means) - np.array(r2_stds),
                            np.array(r2_means) + np.array(r2_stds),
                            alpha=0.1, color=color)

        ax.set_xlabel('Number of Female Training Samples')
        ax.set_ylabel('R²')
        ax.set_title(title)
        ax.legend(loc='lower right', fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.set_ylim([0, 1])
        ax.set_xscale('log')
        ax.set_xticks(n_values)
        ax.set_xticklabels([str(n) for n in n_values])

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'transfer_data_efficiency.png')
    plt.savefig(path, dpi=150, bbox_inches='tight')
    print(f"  Saved: {path}")

    # --- Plot 2: Improvement over female-only ---
    fig2, ax = plt.subplots(figsize=(12, 6))
    fig2.suptitle('R² Improvement Over Female-Only Baseline', fontsize=14, fontweight='bold')

    bar_methods = ['linear_calib', 'residual_rf', 'feature_aug', 'transrf']
    x = np.arange(len(n_values))
    width = 0.8 / len(bar_methods)

    for i, key in enumerate(bar_methods):
        color, _, label = style[key]
        improvements = []
        for r in all_results:
            baseline = (r['female_only_F0_r2_mean'] + r['female_only_SPL_r2_mean']) / 2
            method = (r[f'{key}_F0_r2_mean'] + r[f'{key}_SPL_r2_mean']) / 2
            improvements.append(method - baseline)

        ax.bar(x + i * width, improvements, width, label=label, color=color, alpha=0.8)

    ax.set_xlabel('Number of Female Training Samples')
    ax.set_ylabel('R² Improvement')
    ax.set_xticks(x + width * (len(bar_methods) - 1) / 2)
    ax.set_xticklabels([str(n) for n in n_values])
    ax.axhline(0, color='black', linewidth=1)
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    path2 = os.path.join(OUTPUT_DIR, 'transfer_improvement_over_baseline.png')
    plt.savefig(path2, dpi=150, bbox_inches='tight')
    print(f"  Saved: {path2}")

    # --- Plot 3: Scatter plots for best method at smallest N ---
    smallest = all_results[0]
    n_show = smallest['n_train']

    # rerun once to get actual predictions for plotting
    rng = np.random.RandomState(RANDOM_STATE)
    indices = rng.choice(len(X_pool), size=min(n_show, len(X_pool)), replace=False)
    X_tr = X_pool.iloc[indices].reset_index(drop=True)
    Y_tr = Y_pool[indices]

    preds = {
        'Female Only': method_female_only(X_tr, Y_tr, X_test),
        'Linear Calib': method_linear_calibration(X_tr, Y_tr, X_test, male_model, male_scaler),
        'Feature Aug': method_feature_augmentation(X_tr, Y_tr, X_test, male_model, male_scaler),
        'Male Only': method_source_only(X_test, male_model, male_scaler),
    }

    fig3, axes3 = plt.subplots(2, 4, figsize=(20, 10))
    fig3.suptitle(f'Predicted vs Actual with N={n_show} Female Samples', fontsize=14, fontweight='bold')

    for col, (name, pred) in enumerate(preds.items()):
        for row, (target_idx, target_name, unit) in enumerate([(0, 'F0', 'Hz'), (1, 'SPL', 'dB')]):
            ax = axes3[row, col]
            ax.scatter(Y_test[:, target_idx], pred[:, target_idx], alpha=0.15, s=5)
            lims = [Y_test[:, target_idx].min(), Y_test[:, target_idx].max()]
            ax.plot(lims, lims, 'r--', linewidth=2)
            r2 = r2_score(Y_test[:, target_idx], pred[:, target_idx])
            ax.set_title(f'{name}\n{target_name} R²={r2:.3f}')
            ax.set_xlabel(f'Actual {target_name} ({unit})')
            ax.set_ylabel(f'Predicted {target_name} ({unit})')
            ax.grid(True, alpha=0.3)

    plt.tight_layout()
    path3 = os.path.join(OUTPUT_DIR, f'scatter_N{n_show}.png')
    plt.savefig(path3, dpi=150, bbox_inches='tight')
    print(f"  Saved: {path3}")

    plt.show()

    print("\n" + "=" * 70)
    print("EXPERIMENT COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()
